baseURL = 'https://minimumviablestack.net/'
languageCode = 'en-us'
title = 'Minimal Viable Stack'
theme = 'hugo-whisper-theme'

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Docs"
url = "/docs/"
weight = 2

[params.logo]
  mobile = "/images/logo.png"
  standard  = "/images/logo.png"

[params]
  google_analytics_id="G-MEY8CTXT21"
  homepage_button_link = '/docs'
  homepage_button_text = 'Read MVS'
